export interface Player {
  id: string;
  name: string;
  birthYear: number;
  ageGroup: string;
  position: 'Goalkeeper' | 'Defender' | 'Midfielder' | 'Forward';
  preferredFoot: 'Left' | 'Right' | 'Both';
  squadNumber: number | null;
  avatarSeed: string; // Used for rendering beautiful and consistent avatars
  notes: string;
  createdAt: string;
}

export interface CornerRatings {
  technical: {
    dribbling: number;
    passing: number;
    shooting: number;
    defending: number;
    tactical: number;
  };
  physical: {
    agility: number;
    speed: number;
    stamina: number;
    strength: number;
  };
  psychological: {
    confidence: number;
    focus: number;
    decisionMaking: number;
    resilience: number;
  };
  social: {
    communication: number;
    teamwork: number;
    discipline: number;
    leadership: number;
  };
}

export interface PlayerEvaluation {
  id: string;
  playerId: string;
  date: string;
  ratings: CornerRatings;
  coachNotes: string;
  generatedReport?: string; // Generated by Gemini AI
}
